name: Flutter Asset Manager CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  analyze_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Analyze Code
        run: dart analyze

      - name: Run Tests
        run: dart test